name: CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
      tags:
        description: 'Test scenario tags'
jobs:
  CI_Linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v1
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: package-version
        uses: nyaa8/package-version@v1.0.3
      - name: Setup yarn
        run: npm i -g yarn
      - name: Install JS Modules
        run: yarn install
      - name: Checking code syntax
        run: yarn lint
      #- run: npm test - Fuck this, I'm not going to spend 5 hours debugging why the CI can't start a chrome process
      - run: npm run dist -- LINUX
      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          name: Songs-of-War-Game-linux-${{ env.PACKAGE_VERSION }}.AppImage
          path: dist/Songs-of-War-Game-linux-${{ env.PACKAGE_VERSION }}.AppImage
      - name: Upload latest-linux file
        uses: actions/upload-artifact@v2
        with:
          name: latest-linux.yml
          path: dist/latest-linux.yml
  CI_MacOS:
    runs-on: macos-latest
    strategy:
      matrix:
        operating-system: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v1
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: package-version
        uses: nyaa8/package-version@v1.0.3
      - name: Install JS Modules
        run: yarn install
      - name: Checking code syntax
        run: yarn lint
      #- run: npm test
      - run: npm run dist -- MAC
      - name: Upload dmg
        uses: actions/upload-artifact@v2
        with:
          name: Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.dmg
          path: dist/Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.dmg
      - name: Upload blockmap
        uses: actions/upload-artifact@v2
        with:
          name: Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.dmg.blockmap
          path: dist/Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.dmg.blockmap
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.zip
          path: dist/Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.zip
      - name: Upload zip blockmap
        uses: actions/upload-artifact@v2
        with:
          name: Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.zip.blockmap
          path: dist/Songs-of-War-Game-mac-${{ env.PACKAGE_VERSION }}.zip.blockmap
      - name: Upload latest-mac file
        uses: actions/upload-artifact@v2
        with:
          name: latest-mac.yml
          path: dist/latest-mac.yml
  CI_Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        operating-system: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v1
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: package-version
        uses: nyaa8/package-version@v1.0.3
      - name: Install JS Modules
        run: yarn install
      - name: Checking code syntax
        run: yarn lint
      #- run: npm test
      - run: npm run dist -- WINDOWS
      - name: Upload Artifact 1
        uses: actions/upload-artifact@v2
        with:
          name: songs-of-war-launcher-setup-${{ env.PACKAGE_VERSION }}.exe
          path: dist/songs-of-war-launcher-setup-${{ env.PACKAGE_VERSION }}.exe
      - name: Upload Artifact 2
        uses: actions/upload-artifact@v2
        with:
          name: songs-of-war-launcher-setup-${{ env.PACKAGE_VERSION }}.exe.blockmap
          path: dist/songs-of-war-launcher-setup-${{ env.PACKAGE_VERSION }}.exe.blockmap
      - name: Upload Artifact 3
        uses: actions/upload-artifact@v2
        with:
          name: latest.yml
          path: dist/latest.yml

